### ISSUE TITLE
leafy should support modular gems

### ISSUE THREAD

**Issue by rtyler** [lookout/leafy#1]
Per my discussion with @mkristian in chat, instead of just distributing one big giant gem, leafy should provide modular gems with a monolithic gem which only includes dependencies.

In effect this might be:

 * leafy-metrics
 * leafy-healthchecks

And then a gem with *zero* code in it `leafy` would just declare a dependency on the latest version of all those modular gems.

This will allow developers who want *everything* to just include `gem 'leafy'` whereas developers who want to be more selective can include any single modular gem on its own

**Comment by mkristian** [comment]
I would say there are two more modules:

* leafy-json
* leafy-rack

the json uses the dropwizard-metrics-json arttifact which uses jackson under the hood to serialize the metrics and health data

the rack part would be the counter-part to dropwizard-metrics-servlets

there is one more dropwizard-metrics-servlet (without the 's') which does some intrumentation the HTTP level, which can be easily implemented as well. but could be part of the leafy-rack as well.

**Comment by rtyler** [comment]
@mkristian I'm in agreement with you on `leafy-rack` but I'm not sure why `leafy-json` would be needed. It sounds like it's just something that would be used underneath the metrics gem wouldn't it? Would there be additional user-facing functionality that it would provide?

**Comment by mkristian** [comment]
actually it is needed by leafy-rack to generate the json - not sure if this is used somewhere else. so let's put the json classes to ```leafy-rack```

**Comment by rtyler** [comment]
:1: if we need to refactor it out later, that's fine

**Comment by mkristian** [comment]
blocked by: https://github.com/mkristian/jar-dependencies/issues/13

**Comment by rtyler** [comment]
I don't beleve this is blocked anymore. That said, I think we need a `leafy.gemspec` in the root directory which expresses the gem dependencies on the modular gems, that way I can upload:

 * leafy-health
 * leafy-metrics
 * leafy-rack
 * leafy

**Comment by mkristian** [comment]
fixed via c32a10e9c5ae009e8ce6e12b917eef1a2727f241
