### ISSUE TITLE
[leafy-health] the health-check class should have an abstract class

### ISSUE THREAD

**Issue by mkristian** [lookout/leafy#13]
the abstract class would provide the ```unhealthy``` and ```healthy``` methods

```
class AppCheck < Leafy::Health::AbstractCheck
  def call
    if app.crashed
      unhealthy( 'application crashed' )
    else
      healthy( 'application ok' )
    end
  end
end
```

**Comment by rtyler** [comment]
I would add the additional criteria in that AbstractCheck define `call` such that it always responds unhealthy. Not implementing a `call` method means your service isn't healthy until it's implemented :)

**Comment by mkristian** [comment]
+1
