### ISSUE TITLE
Add leafy-logger to abstract logging

### ISSUE THREAD

**Issue by rtyler** [lookout/leafy#7]
We've done some internal tinkering with exposing [logback](http://logback.qos.ch/) APis into Ruby for better logging.

A leafy/logger module to hold this code I think would be useful

**Comment by rtyler** [comment]
@blaines I'm passing this your way, I think @mkristian may need to finish cleaning up some of the basic component-gem structures before you should tackle this though

**Comment by mkristian** [comment]
I do not think that the current problem with leafy-rack and examples/hellowarld is interferring with any new leafy-logger module/gem. just take leafy-health and/or leafy-metrics as blue print for leafy-logger

**Comment by rtyler** [comment]
I'm going to bounce this out of the initial release since we're not going to get to ti right now

**Comment by polynomial** [comment]
Key things:
it should have similar features to logback: http://logback.qos.ch/faq.html
* squelch logs
* log certain class paths.level combos

The ability for engineers to set a level as part of the log emission (in the code they should  be able to say 'this is CRIT|WARN|INFO'.

*nice to have*: Long term it might be nice to be able to set/define a way to say 'this is a log, but it also has these metrics, and if you get X number of these logs thats also bad'.
